# ==========================================================
# BITS Pilani WILP
# Machine Learning Assignment-2
# Streamlit Web Application
# Heart Disease Prediction
# ==========================================================

import streamlit as st
import pandas as pd
import joblib

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)

# ==========================================================
# Page Configuration
# ==========================================================

st.set_page_config(
    page_title="Heart Disease Prediction",
    page_icon="❤️",
    layout="wide"
)

st.title("❤️ Heart Disease Prediction using Machine Learning")
st.markdown("### BITS Pilani WILP - Machine Learning Assignment 2")
st.markdown("---")

# ==========================================================
# Load Scaler
# ==========================================================

try:
    scaler = joblib.load("models/scaler.pkl")
except Exception as e:
    st.error(f"Unable to load scaler.\n\n{e}")
    st.stop()

# ==========================================================
# Load Models
# ==========================================================

try:

    models = {

        "Logistic Regression":
            (joblib.load("models/logistic.pkl"), True),

        "Decision Tree":
            (joblib.load("models/decision_tree.pkl"), False),

        "K-Nearest Neighbors":
            (joblib.load("models/knn.pkl"), True),

        "Gaussian Naive Bayes":
            (joblib.load("models/naive_bayes.pkl"), True),

        "Random Forest":
            (joblib.load("models/random_forest.pkl"), False)

    }

except Exception as e:

    st.error(f"Unable to load models.\n\n{e}")
    st.stop()

# ==========================================================
# Expected Features
# ==========================================================

FEATURE_COLUMNS = [

    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal"

]

# ==========================================================
# Sidebar
# ==========================================================

st.sidebar.header("Configuration")

selected_model = st.sidebar.selectbox(
    "Select Machine Learning Model",
    list(models.keys())
)

uploaded_file = st.sidebar.file_uploader(
    "Upload test_data.csv",
    type=["csv"]
)

st.sidebar.markdown("---")
st.sidebar.info("Upload the test_data.csv generated by train_models.py")

st.subheader("Selected Model")
st.success(selected_model)

# ==========================================================
# Main
# ==========================================================

if uploaded_file is not None:

    try:

        df = pd.read_csv(uploaded_file)

    except Exception as e:

        st.error(e)

        st.stop()

    st.subheader("Uploaded Dataset")

    st.dataframe(df.head())

    st.write("Rows :", len(df))
    st.write("Columns :", len(df.columns))

    # ======================================================
    # Validate Target
    # ======================================================

    if "target" not in df.columns:

        st.error("Target column 'target' is missing.")

        st.stop()

    # ======================================================
    # Validate Features
    # ======================================================

    missing = []

    for col in FEATURE_COLUMNS:

        if col not in df.columns:

            missing.append(col)

    if len(missing) > 0:

        st.error("Missing Columns")

        st.write(missing)

        st.stop()

    # ======================================================
    # Prepare Data
    # ======================================================

    X = df[FEATURE_COLUMNS].copy()

    y = df["target"]

    model, scaling_required = models[selected_model]

    # ======================================================
    # Scaling
    # ======================================================

    if scaling_required:

        X_input = pd.DataFrame(

            scaler.transform(X),

            columns=X.columns,

            index=X.index

        )

    else:

        X_input = X.copy()

    # ======================================================
    # Prediction
    # ======================================================

    prediction = model.predict(X_input)

    probability = model.predict_proba(X_input)[:, 1]

    # ======================================================
    # Metrics
    # ======================================================

    accuracy = accuracy_score(y, prediction)

    precision = precision_score(y, prediction)

    recall = recall_score(y, prediction)

    f1 = f1_score(y, prediction)

    auc = roc_auc_score(y, probability)

    mcc = matthews_corrcoef(y, prediction)

    st.success("Prediction Completed Successfully")

else:

    st.info("Please upload test_data.csv from the sidebar.")
    # ==========================================================
# Display Results
# ==========================================================

if uploaded_file is not None:

    # ------------------------------------------------------
    # Evaluation Metrics
    # ------------------------------------------------------

    st.markdown("---")
    st.subheader("📊 Model Evaluation Metrics")

    col1, col2, col3 = st.columns(3)

    col1.metric("Accuracy", f"{accuracy:.4f}")
    col2.metric("Precision", f"{precision:.4f}")
    col3.metric("Recall", f"{recall:.4f}")

    col4, col5, col6 = st.columns(3)

    col4.metric("F1 Score", f"{f1:.4f}")
    col5.metric("ROC-AUC", f"{auc:.4f}")
    col6.metric("MCC", f"{mcc:.4f}")

    # ------------------------------------------------------
    # Confusion Matrix
    # ------------------------------------------------------

    st.markdown("---")
    st.subheader("Confusion Matrix")

    cm = confusion_matrix(y, prediction)

    cm_df = pd.DataFrame(
        cm,
        index=["Actual Negative", "Actual Positive"],
        columns=["Predicted Negative", "Predicted Positive"]
    )

    st.dataframe(
        cm_df,
        use_container_width=True
    )

    # ------------------------------------------------------
    # Classification Report
    # ------------------------------------------------------

    st.markdown("---")
    st.subheader("Classification Report")

    report = classification_report(
        y,
        prediction,
        output_dict=True
    )

    report_df = pd.DataFrame(report).transpose()

    st.dataframe(
        report_df.round(4),
        use_container_width=True
    )

    # ------------------------------------------------------
    # Prediction Results
    # ------------------------------------------------------

    st.markdown("---")
    st.subheader("Prediction Results")

    result = X.copy()

    result["Actual"] = y.values
    result["Prediction"] = prediction
    result["Probability"] = probability.round(4)

    st.dataframe(
        result,
        use_container_width=True
    )

    # ------------------------------------------------------
    # Prediction Summary
    # ------------------------------------------------------

    st.markdown("---")
    st.subheader("Prediction Summary")

    summary = pd.DataFrame({
        "Prediction": ["No Heart Disease (0)", "Heart Disease (1)"],
        "Count": [
            (prediction == 0).sum(),
            (prediction == 1).sum()
        ]
    })

    st.dataframe(
        summary,
        use_container_width=True
    )

    # ------------------------------------------------------
    # Download Results
    # ------------------------------------------------------

    csv = result.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="📥 Download Prediction Results",
        data=csv,
        file_name="prediction_results.csv",
        mime="text/csv"
    )

# ==========================================================
# Footer
# ==========================================================

st.markdown("---")

st.markdown(
"""
### BITS Pilani WILP

**Machine Learning Assignment-2**

Heart Disease Prediction using Machine Learning

Developed using:

- Logistic Regression
- Decision Tree
- K-Nearest Neighbors
- Gaussian Naive Bayes
- Random Forest
"""
)